# Generated by Django 3.2 on 2021-04-25 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0006_question_multiple_right_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_selected_option',
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_selected_option', models.ManyToManyField(to='quiz_app.Question')),
            ],
        ),
    ]
