# Generated by Django 3.2 on 2021-04-25 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0007_auto_20210425_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='UserInfo',
        ),
    ]
