# Generated by Django 3.2 on 2021-04-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_rename_user_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='question',
            field=models.ManyToManyField(to='quiz_app.Question'),
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_selected_option',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_selected_option',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
