# Generated by Django 3.2 on 2021-04-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_auto_20210425_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_selected_option',
        ),
        migrations.AddField(
            model_name='question',
            name='user_selected_option',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
