# Generated by Django 3.2 on 2021-04-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_auto_20210425_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_selected_option',
        ),
    ]
