# Generated by Django 3.2 on 2021-04-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0013_remove_question_user_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.TextField(),
        ),
    ]
